genre_weightage = 0.4
tags_weightage = 0.5
instrument_weightage = 1

feature_weights = {
'Engagement' : 0.85,
'danceability' : 0.85,
'mood_acoustic' : 0.70,
'mood_aggressive' : 1,
'mood_electronic' : 0.72,
'mood_happy' : 0.7,
'mood_party' : 0.85,
'mood_relaxed' : 0.80,
'mood_sad' : 0.8,
'tonal' : 0.35,
'Reverb_wet' : 0.55,
'voice_female' : 1,
'voice_male' : 1,
'overall_voice' : 1.2,
'year' : 0.5
}

normalizing_factor = 1.3
normalizing_factor_meta = 0.6
balancing_factor = 0.5


mdata_outliers = ('music lab collective','various artists','halamithi habibo','my best collection','original motion picture soundtrack',
            'original television soundtrack','bollywoods musical extravaganza','original music picture soundtrack','music from the motion picture')

genres = (('Genre_acidjazz', 'Acidjazz'),
 ('Genre_ambient', 'Ambient'),
 ('Genre_atmospheric', 'Atmospheric'),
 ('Genre_blues', 'Blues'),
 ('Genre_bluesrock', 'Bluesrock'),
 ('Genre_breakbeat', 'Breakbeat'),
 ('Genre_chillout', 'Chillout'),
 ('Genre_choir', 'Choir'),
 ('Genre_classical', 'Classical'),
 ('Genre_classicrock', 'Classicrock'),
 ('Genre_club', 'Club'),
 ('Genre_country', 'Country'),
 ('Genre_darkambient', 'Darkambient'),
 ('Genre_darkwave', 'Darkwave'),
 ('Genre_deephouse', 'Deephouse'),
 ('Genre_disco', 'Disco'),
 ('Genre_downtempo', 'Downtempo'),
 ('Genre_drumnbass', 'Drumnbass'),
 ('Genre_dub', 'Dub'),
 ('Genre_dubstep', 'Dubstep'),
 ('Genre_easylistening', 'Easylistening'),
 ('Genre_electronic', 'Electronic'),
 ('Genre_electropop', 'Electropop'),
 ('Genre_ethno', 'Ethno'),
 ('Genre_folk', 'Folk'),
 ('Genre_funk', 'Funk'),
 ('Genre_fusion', 'Fusion'),
 ('Genre_groove', 'Groove'),
 ('Genre_hardrock', 'Hardrock'),
 ('Genre_hiphop', 'Hiphop'),
 ('Genre_house', 'House'),
 ('Genre_indie', 'Indie'),
 ('Genre_industrial', 'Industrial'),
 ('Genre_instrumentalpop', 'Instrumentalpop'),
 ('Genre_instrumentalrock', 'Instrumentalrock'),
 ('Genre_jazz', 'Jazz'),
 ('Genre_jazzfusion', 'Jazzfusion'),
 ('Genre_lounge', 'Lounge'),
 ('Genre_medieval', 'Medieval'),
 ('Genre_metal', 'Metal'),
 ('Genre_orchestral', 'Orchestral'),
 ('Genre_pop', 'Pop'),
 ('Genre_popfolk', 'Popfolk'),
 ('Genre_poprock', 'Poprock'),
 ('Genre_postrock', 'Postrock'),
 ('Genre_punkrock', 'Punkrock'),
 ('Genre_rap', 'Rap'),
 ('Genre_reggae', 'Reggae'),
 ('Genre_rock', 'Rock'),
 ('Genre_rocknroll', 'Rocknroll'),
 ('Genre_symphonic', 'Symphonic'),
 ('Genre_synthpop', 'Synthpop'),
 ('Genre_techno', 'Techno'),
 ('Genre_trance', 'Trance'),
 ('Genre_triphop', 'Triphop'))


tags = (('Tag_ambient', 'Ambient'),
 ('Tag_atmospheric', 'Atmospheric'),
 ('Tag_chillout', 'Chillout'),
 ('Tag_classical', 'Classical'),
 ('Tag_downtempo', 'Downtempo'),
 ('Tag_easylistening', 'Easylistening'),
 ('Tag_electronic', 'Electronic'),
 ('Tag_folk', 'Folk'),
 ('Tag_funk', 'Funk'),
 ('Tag_hiphop', 'Hiphop'),
 ('Tag_house', 'House'),
 ('Tag_indie', 'Indie'),
 ('Tag_instrumentalpop', 'Instrumentalpop'),
 ('Tag_jazz', 'Jazz'),
 ('Tag_metal', 'Metal'),
 ('Tag_newage', 'Newage'),
 ('Tag_orchestral', 'Orchestral'),
 ('Tag_pop', 'Pop'),
 ('Tag_popfolk', 'Popfolk'),
 ('Tag_poprock', 'Poprock'),
 ('Tag_reggae', 'Reggae'),
 ('Tag_rock', 'Rock'),
 ('Tag_techno', 'Techno'),
 ('Tag_triphop', 'Triphop'),
 ('Tag_acousticguitar', 'Acousticguitar'),
 ('Tag_bass', 'Bass'),
 ('Tag_drummachine', 'Drummachine'),
 ('Tag_drums', 'Drums'),
 ('Tag_electricguitar', 'Electricguitar'),
 ('Tag_electricpiano', 'Electricpiano'),
 ('Tag_guitar', 'Guitar'),
 ('Tag_keyboard', 'Keyboard'),
 ('Tag_piano', 'Piano'),
 ('Tag_strings', 'Strings'),
 ('Tag_synthesizer', 'Synthesizer'),
 ('Tag_violin', 'Violin'),
 ('Tag_emotional', 'Emotional'),
 ('Tag_film', 'Film'),
 ('Tag_relaxing', 'Relaxing'))