# Generated by Django 4.2.1 on 2023-05-30 08:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('audio_file', models.FileField(upload_to='audio', validators=[django.core.validators.FileExtensionValidator(['m4a', 'mp3', 'wav'])])),
                ('artist', models.CharField(blank=True, max_length=80, null=True)),
                ('album', models.CharField(blank=True, max_length=80, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('album_artist', models.CharField(blank=True, max_length=80, null=True)),
                ('track_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('artwork', models.ImageField(blank=True, default='cover_images/default.jpg', null=True, upload_to='cover_images')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('ambient', 'Ambient'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('indie', 'Indie'), ('metal', 'Metal'), ('orchestral', 'Orchestral'), ('pop', 'Pop'), ('rock', 'Rock'), ('funk', 'Funk'), ('hiphop', 'Hip-hop'), ('techno', 'Techno')], default=None, max_length=25, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
        ),
    ]
