# Generated by Django 4.2.1 on 2023-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
