# Generated by Django 4.2.1 on 2023-05-31 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_song_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(max_length=200, upload_to='audio', validators=[django.core.validators.FileExtensionValidator(['m4a', 'mp3', 'wav'])]),
        ),
    ]
