# Generated by Django 4.2.1 on 2023-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_album_alter_song_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, default='cover_images/default.png', max_length=250, null=True, upload_to='cover_images'),
        ),
    ]
