# Generated by Django 4.2.1 on 2023-05-31 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_song_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_artist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, default='cover_images/default.png', max_length=350, null=True, upload_to='cover_images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(max_length=350, upload_to='audio', validators=[django.core.validators.FileExtensionValidator(['m4a', 'mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
