# Generated by Django 4.2.1 on 2023-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_song_original_filename_alter_song_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.PositiveIntegerField()),
                ('original_name', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='original_filename',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
