# Generated by Django 4.2.1 on 2023-05-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_song_id_alter_song_original_filename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song_ID',
        ),
    ]
