# Generated by Django 4.2.1 on 2023-06-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, choices=[('Tag_ambient', 'Ambient'), ('Tag_atmospheric', 'Atmospheric'), ('Tag_chillout', 'Chillout'), ('Tag_classical', 'Classical'), ('Tag_downtempo', 'Downtempo'), ('Tag_easylistening', 'Easylistening'), ('Tag_electronic', 'Electronic'), ('Tag_folk', 'Folk'), ('Tag_funk', 'Funk'), ('Tag_hiphop', 'Hiphop'), ('Tag_house', 'House'), ('Tag_indie', 'Indie'), ('Tag_instrumentalpop', 'Instrumentalpop'), ('Tag_jazz', 'Jazz'), ('Tag_metal', 'Metal'), ('Tag_newage', 'Newage'), ('Tag_orchestral', 'Orchestral'), ('Tag_pop', 'Pop'), ('Tag_popfolk', 'Popfolk'), ('Tag_poprock', 'Poprock'), ('Tag_reggae', 'Reggae'), ('Tag_rock', 'Rock'), ('Tag_techno', 'Techno'), ('Tag_triphop', 'Triphop'), ('Tag_acousticguitar', 'Acousticguitar'), ('Tag_bass', 'Bass'), ('Tag_drummachine', 'Drummachine'), ('Tag_drums', 'Drums'), ('Tag_electricguitar', 'Electricguitar'), ('Tag_electricpiano', 'Electricpiano'), ('Tag_guitar', 'Guitar'), ('Tag_keyboard', 'Keyboard'), ('Tag_piano', 'Piano'), ('Tag_strings', 'Strings'), ('Tag_synthesizer', 'Synthesizer'), ('Tag_violin', 'Violin'), ('Tag_emotional', 'Emotional'), ('Tag_film', 'Film'), ('Tag_relaxing', 'Relaxing')], default=None, max_length=35, null=True),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Genre_acidjazz', 'Acidjazz'), ('Genre_ambient', 'Ambient'), ('Genre_atmospheric', 'Atmospheric'), ('Genre_blues', 'Blues'), ('Genre_bluesrock', 'Bluesrock'), ('Genre_breakbeat', 'Breakbeat'), ('Genre_chillout', 'Chillout'), ('Genre_choir', 'Choir'), ('Genre_classical', 'Classical'), ('Genre_classicrock', 'Classicrock'), ('Genre_club', 'Club'), ('Genre_country', 'Country'), ('Genre_darkambient', 'Darkambient'), ('Genre_darkwave', 'Darkwave'), ('Genre_deephouse', 'Deephouse'), ('Genre_disco', 'Disco'), ('Genre_downtempo', 'Downtempo'), ('Genre_drumnbass', 'Drumnbass'), ('Genre_dub', 'Dub'), ('Genre_dubstep', 'Dubstep'), ('Genre_easylistening', 'Easylistening'), ('Genre_electronic', 'Electronic'), ('Genre_electropop', 'Electropop'), ('Genre_ethno', 'Ethno'), ('Genre_folk', 'Folk'), ('Genre_funk', 'Funk'), ('Genre_fusion', 'Fusion'), ('Genre_groove', 'Groove'), ('Genre_hardrock', 'Hardrock'), ('Genre_hiphop', 'Hiphop'), ('Genre_house', 'House'), ('Genre_indie', 'Indie'), ('Genre_industrial', 'Industrial'), ('Genre_instrumentalpop', 'Instrumentalpop'), ('Genre_instrumentalrock', 'Instrumentalrock'), ('Genre_jazz', 'Jazz'), ('Genre_jazzfusion', 'Jazzfusion'), ('Genre_lounge', 'Lounge'), ('Genre_medieval', 'Medieval'), ('Genre_metal', 'Metal'), ('Genre_orchestral', 'Orchestral'), ('Genre_pop', 'Pop'), ('Genre_popfolk', 'Popfolk'), ('Genre_poprock', 'Poprock'), ('Genre_postrock', 'Postrock'), ('Genre_punkrock', 'Punkrock'), ('Genre_rap', 'Rap'), ('Genre_reggae', 'Reggae'), ('Genre_rock', 'Rock'), ('Genre_rocknroll', 'Rocknroll'), ('Genre_symphonic', 'Symphonic'), ('Genre_synthpop', 'Synthpop'), ('Genre_techno', 'Techno'), ('Genre_trance', 'Trance'), ('Genre_triphop', 'Triphop')], default=None, max_length=35, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
        ),
    ]
