# Generated by Django 4.2.1 on 2023-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tag_score_alter_tag_name_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics2',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='original_filename',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
