# Generated by Django 4.2.1 on 2023-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_song_lyrics2_alter_song_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
