# Generated by Django 4.2.1 on 2023-06-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_song_lyrics2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
    ]
