# Generated by Django 4.2.1 on 2023-06-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_song_lyrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='lyrics2',
            new_name='lyrics',
        ),
    ]
