# Generated by Django 4.2.1 on 2023-06-09 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_rename_lyrics2_song_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.FloatField()),
                ('engagement', models.FloatField()),
                ('instrument', models.FloatField()),
                ('danceability', models.FloatField()),
                ('acoustics', models.FloatField()),
                ('aggressive', models.FloatField()),
                ('happy', models.FloatField()),
                ('party', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
