# Generated by Django 4.2.1 on 2023-06-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
